package com.calyx.app.ui.share

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.LinearGradient
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Shader
import android.graphics.Typeface
import androidx.core.content.FileProvider
import com.calyx.app.data.models.CallerStats
import com.calyx.app.data.models.RankingCategory
import com.calyx.app.utils.DurationFormatter
import com.calyx.app.utils.PhoneNumberUtils
import java.io.File
import java.io.FileOutputStream

/**
 * Share Poster Generator - Creates a 1080x1920 (9:16) image for social sharing.
 * 
 * Design:
 * - Background: Dark nature/forest theme
 * - Header: "My Circle" + App Logo
 * - Center: Top 3 Podium (large)
 * - Lower: Two-column grid for ranks 4-10
 * - Footer: "Generated by Calyz"
 */
object SharePosterGenerator {
    
    private const val POSTER_WIDTH = 1080
    private const val POSTER_HEIGHT = 1920
    
    /**
     * Generate and share a poster with the top 10 contacts.
     * Uses Canvas-based rendering to avoid Compose window attachment issues.
     */
    fun shareTopContacts(
        context: Context,
        topContacts: List<CallerStats>,
        category: RankingCategory
    ) {
        try {
            // Create bitmap using Canvas-based rendering
            val bitmap = createPosterBitmap(context, topContacts.take(10), category)
            
            // Save to cache and share
            val file = saveBitmapToCache(context, bitmap)
            shareBitmap(context, file)
        } catch (e: Exception) {
            e.printStackTrace()
            // Fallback: Share as text if bitmap generation fails
            shareAsText(context, topContacts.take(10), category)
        }
    }
    
    /**
     * Create the poster bitmap using Canvas and Paint APIs.
     * Matches the User's "Sage Green Story" design.
     */
    private fun createPosterBitmap(
        context: Context,
        topContacts: List<CallerStats>,
        category: RankingCategory
    ): Bitmap {
        // 1. Load the Template
        val options = android.graphics.BitmapFactory.Options().apply {
            inMutable = true
            inScaled = false
        }
        val template = android.graphics.BitmapFactory.decodeResource(
            context.resources, 
            com.calyx.app.R.drawable.share_template,
            options
        )
        
        val bitmap = template.copy(Bitmap.Config.ARGB_8888, true)
        val canvas = Canvas(bitmap)
        
        // 2. Overlay User Handle
        val prefs = context.getSharedPreferences("calyz_prefs", Context.MODE_PRIVATE)
        val userName = prefs.getString("user_name", "USER")?.uppercase() ?: "USER"
        
        val usernamePaint = Paint().apply {
            color = 0xCCFFFFFF.toInt() // 80% White
            textSize = 34f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
            textAlign = Paint.Align.CENTER
            isAntiAlias = true
            letterSpacing = 0.15f
        }
        // Template already has @USERNAME placeholder, we cover it
        // Positioning it roughly at Y=175f based on template visual
        canvas.drawText("@$userName", POSTER_WIDTH / 2f, 178f, usernamePaint)
        
        // 3. Top 3 Podium Dynamic Data
        if (topContacts.isNotEmpty()) {
            drawPodium(context, canvas, topContacts.take(3), category)
        }
        
        // 4. Remaining List (4-10)
        val remaining = topContacts.drop(3).take(7)
        if (remaining.isNotEmpty()) {
            drawSimpleList(canvas, remaining, category)
        }
        
        return bitmap
    }
    
    private fun drawPodium(context: Context, canvas: Canvas, top3: List<CallerStats>, category: RankingCategory) {
        // Positions refined to match share_template.png
        
        // Helper to get formatted score
        fun getScore(c: CallerStats): String = when (category) {
            RankingCategory.MOST_CALLED -> "${c.totalCalls} Calls"
            RankingCategory.MOST_TALKED -> DurationFormatter.formatShort(c.totalDuration)
        }
        
        // Draw #2 (Left Arch)
        if (top3.size >= 2) {
            drawArchItem(
                context, canvas, top3[1], 
                cx = 230f, 
                cy = 585f, 
                width = 200f, 
                height = 360f,
                score = getScore(top3[1])
            )
        }
        
        // Draw #3 (Right Arch)
        if (top3.size >= 3) {
            drawArchItem(
                context, canvas, top3[2], 
                cx = 850f, 
                cy = 585f, 
                width = 200f, 
                height = 360f,
                score = getScore(top3[2])
            )
        }
        
        // Draw #1 (Center Sunburst)
        if (top3.isNotEmpty()) {
            drawStarburstItem(
                context, canvas, top3[0], 
                cx = POSTER_WIDTH / 2f, 
                cy = 535f, 
                radius = 160f,
                score = getScore(top3[0])
            )
        }
    }
    
    // Draw #1 Rank with Starburst/Sunburst effect
    private fun drawStarburstItem(
        context: Context, 
        canvas: Canvas, 
        caller: CallerStats, 
        cx: Float, 
        cy: Float, 
        radius: Float,
        score: String
    ) {
        // 1. Draw Photo (Circular Clip) - The starburst is already in the template
        val photoRadius = radius
        val photoBitmap = loadContactPhoto(context, caller.profilePhotoUri, (photoRadius * 2).toInt())
        
        canvas.save()
        val photoPath = android.graphics.Path().apply {
            addCircle(cx, cy, photoRadius, android.graphics.Path.Direction.CW)
        }
        canvas.clipPath(photoPath)
        
        if (photoBitmap != null) {
            val srcRect = android.graphics.Rect(0, 0, photoBitmap.width, photoBitmap.height)
            val dstRect = RectF(cx - photoRadius, cy - photoRadius, cx + photoRadius, cy + photoRadius)
            canvas.drawBitmap(photoBitmap, srcRect, dstRect, null)
        } else {
            // Placeholder: matching the sage green theme
            canvas.drawColor(0xFF81C784.toInt())
        }
        canvas.restore()
        
        // 2. Text Below
        // Cover "[] Calls" and "Name" placeholders
        val scoreY = cy + radius + 115f
        val nameY = scoreY + 45f
        
        drawTextInfo(canvas, score, caller.displayName, cx, scoreY, nameY, isCenter = true)
    }

    // Draw #2 and #3 with Arch Shape
    private fun drawArchItem(
        context: Context,
        canvas: Canvas,
        caller: CallerStats,
        cx: Float,
        cy: Float,
        width: Float,
        height: Float,
        score: String
    ) {
        val halfW = width / 2
        val halfH = height / 2
        
        // 1. Draw Photo Clipped to Arch
        val photoBitmap = loadContactPhoto(context, caller.profilePhotoUri, width.toInt())
        
        canvas.save()
        val path = android.graphics.Path()
        val rect = RectF(cx - halfW, cy - halfH, cx + halfW, cy + halfH)
        
        // Arch Window Shape
        path.addRoundRect(rect, floatArrayOf(
            width/2, width/2, // Top-left
            width/2, width/2, // Top-right
            0f, 0f,           // Bottom-right
            0f, 0f            // Bottom-left
        ), android.graphics.Path.Direction.CW)
        
        canvas.clipPath(path)
        
        if (photoBitmap != null) {
            val scale = maxOf(width / photoBitmap.width, height / photoBitmap.height)
            val scaledW = photoBitmap.width * scale
            val scaledH = photoBitmap.height * scale
            val dx = cx - scaledW / 2
            val dy = cy - scaledH / 2
            val dstRect = RectF(dx, dy, dx + scaledW, dy + scaledH)
            
            canvas.drawBitmap(photoBitmap, null, dstRect, null)
        } else {
             canvas.drawColor(0xFF4A6B5C.toInt())
        }
        canvas.restore()
        
        // 2. Text Below
        val scoreY = cy + halfH + 42f
        val nameY = scoreY + 38f
        drawTextInfo(canvas, score, caller.displayName, cx, scoreY, nameY, isCenter = false)
    }
    
    private fun drawTextInfo(canvas: Canvas, score: String, name: String, x: Float, scoreY: Float, nameY: Float, isCenter: Boolean) {
        // Background color covering to hide placeholders if they don't perfectly align
        val bgPaint = Paint().apply {
            color = 0xFF6B8E63.toInt() // Template Background Color
        }
        
        // Cover Score Placeholder
        val scoreWidth = if (isCenter) 250f else 180f
        canvas.drawRect(x - scoreWidth/2, scoreY - 40f, x + scoreWidth/2, scoreY + 10f, bgPaint)
        
        // Score Paint
        val scorePaint = Paint().apply {
            color = 0xFFFFFFFF.toInt()
            textSize = if (isCenter) 42f else 32f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
            textAlign = Paint.Align.CENTER
            isAntiAlias = true
        }
        canvas.drawText(score, x, scoreY, scorePaint)
        
        // Cover Name Placeholder
        val nameWidth = if (isCenter) 300f else 200f
        canvas.drawRect(x - nameWidth/2, nameY - 30f, x + nameWidth/2, nameY + 10f, bgPaint)
        
        // Name Paint
        val namePaint = Paint().apply {
            color = 0xCCFFFFFF.toInt()
            textSize = if (isCenter) 28f else 22f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
            textAlign = Paint.Align.CENTER
            isAntiAlias = true
        }
        val safeName = PhoneNumberUtils.getDisplayName(name, "").take(14)
        canvas.drawText(safeName, x, nameY, namePaint)
    }
    
    private fun drawSimpleList(canvas: Canvas, remaining: List<CallerStats>, category: RankingCategory) {
        val startY = 1118f
        val lineHeight = 92f
        
        // Cover background for list placeholders
        val bgPaint = Paint().apply {
            color = 0xFF6B8E63.toInt()
        }
        
        // Text Paints
        val rankNamePaint = Paint().apply {
            color = 0xFFFFFFFF.toInt()
            textSize = 34f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
            textAlign = Paint.Align.LEFT
            isAntiAlias = true
        }
        
        val scorePaint = Paint().apply {
            color = 0xFFFFFFFF.toInt()
            textSize = 34f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
            textAlign = Paint.Align.RIGHT
            isAntiAlias = true
        }
        
        val leftAnchor = 118f
        val rightAnchor = POSTER_WIDTH - 118f
        val listWidth = 350f
        
        remaining.forEachIndexed { index, caller ->
            val y = startY + (index * lineHeight)
            val rank = 4 + index
            
            // Cover placeholders
            canvas.drawRect(leftAnchor, y - 35f, leftAnchor + listWidth, y + 10f, bgPaint)
            canvas.drawRect(rightAnchor - listWidth, y - 35f, rightAnchor, y + 10f, bgPaint)
            
            // "4. Name"
            val dispName = PhoneNumberUtils.getDisplayName(caller.displayName, caller.phoneNumber)
            val safeName = if (dispName.length > 20) dispName.take(18) + ".." else dispName
            canvas.drawText("$rank. $safeName", leftAnchor, y, rankNamePaint)
            
            // "[x] calls"
            val scoreText = when (category) {
                RankingCategory.MOST_CALLED -> "${caller.totalCalls} calls"
                RankingCategory.MOST_TALKED -> DurationFormatter.formatShort(caller.totalDuration).lowercase()
            }
            canvas.drawText(scoreText, rightAnchor, y, scorePaint)
        }
    }
    
    private fun loadContactPhoto(context: Context, uriString: String?, reqSize: Int): Bitmap? {
        if (uriString.isNullOrEmpty()) return null
        
        return try {
            val uri = android.net.Uri.parse(uriString)
            // Use standard BitmapFactory with stream
            context.contentResolver.openInputStream(uri)?.use { stream ->
                // Decode bounds only first
                // For simplicity, just decoding roughly. In production, use Just-In-Time scaling.
                android.graphics.BitmapFactory.decodeStream(stream)
            }
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }
    
    // ... [Cache saving and Sharing methods remain unchanged] ...
    private fun saveBitmapToCache(context: Context, bitmap: Bitmap): File {
        val cacheDir = File(context.cacheDir, "share")
        cacheDir.mkdirs()
        val file = File(cacheDir, "my_circle_${System.currentTimeMillis()}.png")
        FileOutputStream(file).use { out ->
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, out)
        }
        return file
    }
    
    private fun shareBitmap(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "image/png"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        context.startActivity(Intent.createChooser(shareIntent, "Share your circle"))
    }
    
    private fun shareAsText(context: Context, topContacts: List<CallerStats>, category: RankingCategory) {
        // ... (Keep existing text fallback)
        val text = "Check out my Calyz stats!"
        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        context.startActivity(Intent.createChooser(shareIntent, "Share"))
    }
}
